import { ImCancelCircle } from "react-icons/im";
export const allAssetList = [
  {
    name: "Office WorkStation",
    category: "SoftWare",
    quantity: "15 Units",
    location: "General Office 1",
    edit: "edit",
    assign: "assign",
    office: "Office Workstation",
    remove: <ImCancelCircle />,
  },
  {
    name: "LG split  Unit Air Conditione",
    category: "SoftWare",
    quantity: "15 Units",
    location: "General Office 1",
    edit: "edit",
    assign: "assign",
    office: "Office Workstation",
    remove: <ImCancelCircle />,
  },
  {
    name: "Office WorkStation",
    category: "SoftWare",
    quantity: "15 Units",
    location: "General Office 1",
    edit: "edit",
    assign: "assign",
    office: "Office Workstation",
    remove: <ImCancelCircle />,
  },
  {
    name: "Office WorkStation",
    category: "SoftWare",
    quantity: "15 Units",
    location: "General Office 1",
    edit: "edit",
    assign: "assign",
    office: "Office Workstation",
    remove: <ImCancelCircle />,
  },
  {
    name: "LG split  Unit Air Conditione",
    category: "SoftWare",
    quantity: "15 Units",
    location: "General Office 1",
    edit: "edit",
    assign: "assign",
    office: "Office Workstation",
    remove: <ImCancelCircle />,
  },

  {
    name: "LG split  Unit Air Conditione",
    category: "SoftWare",
    quantity: "15 Units",
    location: "General Office 1",
    edit: "edit",
    assign: "assign",
    office: "Office Workstation",
    remove: <ImCancelCircle />,
  },
];
